import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:4200';
for(const engine of [chromium,webkit]){
 const browser=await engine.launch();try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#name').fill('Careful host');await page.getByRole('button',{name:'Create room',exact:true}).click();await page.locator('.room-code').waitFor();const first=await page.evaluate(()=>JSON.parse(localStorage.getItem('asl-mafia-seat-v2')));const seats=[first];const code=first.code;
 async function api(i,action,extra={}){const r=await fetch(`${base}/api`,{method:'POST',headers:{'Content-Type':'application/json',...(seats[i]?{Authorization:`Bearer ${seats[i].token}`}:{})},body:JSON.stringify({code,action,...extra})});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;}
 await page.getByRole('button',{name:'About mafia',exact:true}).click();await page.locator('#help-popover').waitFor();assert.match(await page.locator('#help-popover').textContent(),/outnumber/);await page.keyboard.press('Escape');assert.equal(await page.locator('#help-popover').isVisible(),false);
 await page.locator('#sheriff').uncheck();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.locator('#sheriff:checked').waitFor();assert.equal((await api(0,'state')).state.config.sheriff,true);
 for(let i=1;i<5;i++){const d=await api(i,'join',{name:`Careful ${i}`});seats.push({code,token:d.token});}
 async function confirmClick(p,selector,accept,pattern){await p.locator(selector).click();await p.locator('#confirm-dialog[open]').waitFor();if(pattern)assert.match(await p.locator('#confirm-dialog').textContent(),pattern);assert.equal(await p.locator('#confirm-cancel').evaluate(el=>el===document.activeElement),true);await p.locator(accept?'#confirm-accept':'#confirm-cancel').click();}
 await confirmClick(page,'[data-action=start]',false,/deal secret roles/);assert.equal((await api(0,'state')).state.phase,'lobby');await confirmClick(page,'[data-action=start]',true);await page.locator('[data-action=reveal]').click();await page.locator('[data-action=ready]').click();await page.locator('[data-action=unready]').click();await page.getByRole('heading',{name:'Check your role'}).waitFor();assert.equal((await api(0,'state')).state.me.submitted,false);
 let state=(await api(0,'state')).state;for(let i=1;i<5;i++)await api(i,'ready',{stage:state.stage});await page.locator('[data-action=reveal]').click();await page.locator('[data-action=ready]').click();await page.locator('#app[data-phase=night]').waitFor();
 const states=await Promise.all(seats.map((_,i)=>api(i,'state').then(d=>d.state)));assert.ok(states.every(s=>s.phase==='night'));const mafia=states.findIndex(s=>s.me.role==='mafia'),town=states.findIndex(s=>s.me.role==='town');
 const mc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mc.addInitScript(seat=>localStorage.setItem('asl-mafia-seat-v2',JSON.stringify(seat)),seats[mafia]);const mp=await mc.newPage();await mp.goto(base);await mp.locator('[data-action=reveal]').click();const target=states[town].me.id;
 await mp.locator(`[data-choice="${target}"]`).click();await mp.locator('[data-action=clear-choice]').click();assert.equal(await mp.locator('[data-action=choose]').isDisabled(),true);await mp.locator(`[data-choice="${target}"]`).click();await confirmClick(mp,'[data-action=choose]',false,/final/);assert.equal((await api(mafia,'state')).state.me.submitted,false);await confirmClick(mp,'[data-action=choose]',true,new RegExp(states[town].me.name));await mp.getByRole('heading',{name:'Choice submitted'}).waitFor();assert.equal((await api(mafia,'state')).state.me.submitted,true);
 assert.deepEqual(errors,[]);console.log(`PASS ${engine.name()}: tappable help and Escape; settings undo; cancelled start; readiness undo; final readiness; clear selection; cancelled and confirmed named night choice.`);
 }finally{await browser.close();}
}
