import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:4201';
for(const engine of [chromium,webkit]){const browser=await engine.launch();try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});await context.addInitScript(()=>localStorage.setItem('asl-mafia-seat-v2',JSON.stringify({code:'ABC234',token:'fixture'})));const p=await context.newPage();
 let ready=0,release;const gate=new Promise(r=>release=r);let state={revision:1,code:'ABC234',host:'0',stage:1,phase:'roles',round:1,config:{mafia:1,sheriff:true,angel:true,angelFrequency:'every',angelCountOn:'use'},me:{id:'0',role:'mafia',alive:true,submitted:false},players:['Ralf','Sam','Jo','Nina','Alex'].map((name,i)=>({id:String(i),name,alive:true,submitted:false})),team:[],submitted:0};
 await p.route('**/api',async r=>{const a=r.request().postDataJSON().action;if(a==='ready'){ready++;if(ready===1){await gate;return r.fulfill({status:503,json:{error:'Could not save. Try again.'}});}state={...state,revision:2,submitted:1,me:{...state.me,submitted:true}};}return r.fulfill({json:{state}});});
 await p.goto(base);await p.locator('[data-action=reveal]').click();assert.equal(await p.locator('[data-action=hide]').count(),0);const know=p.getByRole('button',{name:'I know my role',exact:true});await know.click();await p.getByRole('button',{name:'Getting ready…'}).waitFor();assert.equal(await p.locator('.secret-card').isVisible(),true);assert.equal(await p.locator('#confirm-dialog').isVisible(),false);release();await p.locator('#error:not(:empty)').waitFor();assert.equal(await know.isEnabled(),true);assert.equal(await p.locator('.secret-card').isVisible(),true);
 await know.click();await p.getByRole('heading',{name:'Waiting for players'}).waitFor();assert.equal(await p.locator('.secret-card').count(),0);await p.locator('[data-action=reveal]').click();assert.equal(await p.locator('[data-action=hide]').count(),0);await know.click();await p.getByRole('heading',{name:'Waiting for players'}).waitFor();assert.equal(ready,2,'Re-reading an acknowledged role must not submit readiness again');console.log(`PASS ${engine.name()}: one acknowledgment action; no manual hide; failed save retains role; success hides it; re-read closes without duplicate submission.`);
}finally{await browser.close();}}
