import {chromium,webkit} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:4188';
async function api(action,seat,extra={}){const res=await fetch(base+'/api',{method:'POST',headers:{'Content-Type':'application/json',...(seat?{Authorization:`Bearer ${seat.token}`}:{})},body:JSON.stringify({action,...(seat?{code:seat.state.code,stage:seat.state.stage}:{}),...extra})});const data=await res.json();assert.equal(res.status,200,data.error);return {...seat,...data};}
const browser=await (process.env.BROWSER==='webkit'?webkit:chromium).launch();const failures=[];
async function run(name,fn){try{await fn();console.log('PASS '+name);}catch(e){failures.push({name,error:e.message});console.log('FAIL '+name+': '+e.message);}}
try{
 await run('Failed join keeps typed inputs and recovers with a valid code',async()=>{const host=await api('create',null,{name:'Recovery host'});const c=await browser.newContext();const p=await c.newPage();await p.goto(base+'/?room=222222');await p.locator('#name').fill('Retry player');await p.locator('[type=submit]').click();await p.locator('#error:not(:empty)').waitFor();assert.equal(await p.locator('#name').inputValue(),'Retry player');await p.locator('#code').fill(host.state.code);await p.locator('[type=submit]').click();await p.locator('.room-code').waitFor();await c.close();});
 await run('Resume remains available after switching entry tabs',async()=>{const c=await browser.newContext();const p=await c.newPage();p.on('dialog',d=>d.accept());await p.goto(base);await p.locator('#name').fill('Resume player');await p.locator('[type=submit]').click();await p.locator('.room-code').waitFor();const code=await p.locator('.room-code').textContent();await p.locator('#exit').click();await p.locator('[data-action=resume]').waitFor();await p.locator('[data-mode=join]').click();assert.equal(await p.locator('[data-action=resume]').count(),1,'Switching tabs removed the only Resume control');await p.locator('[data-action=resume]').click();await p.locator('.room-code').waitFor();assert.equal(await p.locator('.room-code').textContent(),code);await c.close();});
 await run('Removed seat returns to a usable join screen instead of retrying forever',async()=>{let host=await api('create',null,{name:'Remove host'}),guest=await api('join',null,{name:'Removed guest',code:host.state.code});const c=await browser.newContext();await c.addInitScript(seat=>localStorage.setItem('asl-mafia-seat-v2',JSON.stringify(seat)),{code:guest.state.code,token:guest.token});const p=await c.newPage();await p.goto(base);await p.locator('.room-code').waitFor();host=await api('remove',host,{target:guest.state.me.id});await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await p.waitForFunction(()=>document.querySelector('#name')!==null,{},{timeout:7000});assert.equal(await p.evaluate(()=>localStorage.getItem('asl-mafia-seat-v2')),null);await c.close();});
 await run('A missing saved room clears the stale seat and permits a new game',async()=>{const c=await browser.newContext();await c.addInitScript(()=>localStorage.setItem('asl-mafia-seat-v2',JSON.stringify({code:'222222',token:'expired-test-seat'})));const p=await c.newPage();await p.goto(base);await p.locator('#error:not(:empty)').waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('asl-mafia-seat-v2')),null);assert.equal(await p.locator('#connection').isVisible(),false);await p.locator('#name').fill('Fresh start');await p.locator('[type=submit]').click();await p.locator('.room-code').waitFor();await c.close();});
 await run('Network failure preserves a private choice and reconnect completes the night',async()=>{let host=await api('create',null,{name:'Offline host'});const seats=[host];for(let i=1;i<5;i++)seats.push(await api('join',null,{name:`Offline ${i}`,code:host.state.code}));seats[0]=await api('start',seats[0]);for(let i=0;i<5;i++)seats[i]=await api('state',seats[i]);await Promise.all(seats.map(s=>api('ready',s)));for(let i=0;i<5;i++)seats[i]=await api('state',seats[i]);const sheriff=seats.find(s=>s.state.me.role==='sheriff'),mafia=seats.find(s=>s.state.me.role==='mafia'),target=seats.find(s=>s.state.me.role==='town');const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await c.addInitScript(seat=>localStorage.setItem('asl-mafia-seat-v2',JSON.stringify(seat)),{code:sheriff.state.code,token:sheriff.token});const p=await c.newPage();p.on('dialog',d=>d.accept());await p.goto(base);await p.locator('[data-action=reveal]').click();await p.locator(`[data-choice="${mafia.state.me.id}"]`).click();await c.setOffline(true);await p.locator('[data-action=choose]').click();await p.locator('#error:not(:empty)').waitFor();assert.equal(await p.locator(`[data-choice="${mafia.state.me.id}"]`).getAttribute('aria-pressed'),'true');assert.equal(await p.locator('[data-action=choose]').isEnabled(),true);await c.setOffline(false);await p.locator('[data-action=choose]').click();await p.getByRole('heading',{name:'Choice submitted',exact:true}).waitFor();await Promise.all(seats.filter(s=>s!==sheriff&&s.state.me.nightActionRequired).map(s=>api('choose',s,{target:s.state.me.role==='mafia'?target.state.me.id:s.state.me.role==='angel'?target.state.me.id:'sleep'})));await p.waitForFunction(()=>document.querySelector('#app')?.dataset.phase==='discussion');await p.locator('[data-action=reveal]').click();await p.getByText(`${mafia.state.me.name} is mafia.`,{exact:false}).waitFor();await p.reload();await p.locator('[data-action=reveal]').waitFor();assert.equal(await p.locator('.secret-card').count(),0);await c.close();});
}finally{await browser.close();}
if(failures.length){console.log(JSON.stringify(failures,null,2));process.exitCode=1;}
